sudo: false

os:
 - linux
 - osx

language: d

d:
 - dmd-2.069.0-b1
 - dmd-2.068.2
 - dmd-2.067.1
 - dmd-2.066.1
 - ldc-0.16.0-beta2
 - ldc-0.15.2-beta2
 - ldc-0.15.1
 - gdc-4.9.2
 - gdc-5.2.0

matrix:
  allow_failures:
   - os: osx
     d: gdc-4.9.2
   - os: osx
     d: gdc-5.2.0
   - os: linux
     d: ldc-0.15.2-beta2

before_script:
  - wget https://github.com/clMathLibraries/clFFT/releases/download/v2.6/clFFT-2.6.0-Linux-x64.tar.gz -O /tmp/clFFT-2.6.0-Linux-x64.tar.gz
  - tar -xvf /tmp/clFFT-2.6.0-Linux-x64.tar.gz
  - export LIBRARY_PATH=$LIBRARY_PATH:$PWD/clFFT-2.6.0-Linux-x64/lib64/
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD/clFFT-2.6.0-Linux-x64/lib64/
